CREATE USER DSY2207
IDENTIFIED BY "ActSum.DYS_01"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION, RESOURCE TO DSY2207;

ALTER USER DSY2207
DEFAULT ROLE RESOURCE;



CREATE TABLE usuarios (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre VARCHAR2(100),
                          email VARCHAR2(100)
);

CREATE TABLE autores (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nombre VARCHAR2(100),
                         nacionalidad VARCHAR2(100)
);

CREATE TABLE libros (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        titulo VARCHAR2(200),
                        autor_id NUMBER,
                        disponible NUMBER(3),
                        FOREIGN KEY (autor_id) REFERENCES autores(id)
);

CREATE TABLE prestamos (
                           id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           usuario_id NUMBER,
                           libro_id NUMBER,
                           fecha_prestamo DATE,
                           fecha_devolucion DATE,
                           estado VARCHAR2(20) DEFAULT 'ACTIVO',
                           FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
                           FOREIGN KEY (libro_id) REFERENCES libros(id)
);
