spring.application.name=bff-service
server.port=8080

functions.usuarios.url=${FUNCTIONS_USUARIOS_URL:https://biblioteca-evcwgpbpbwfqfnfh.westus2-01.azurewebsites.net/api/usuarios}
functions.prestamos.url=${FUNCTIONS_PRESTAMOS_URL:https://biblioteca-evcwgpbpbwfqfnfh.westus2-01.azurewebsites.net/api/prestamos}
functions.libros.url=${FUNCTIONS_LIBROS_URL:https://biblioteca-evcwgpbpbwfqfnfh.westus2-01.azurewebsites.net/api/libros}
functions.autores.url=${FUNCTIONS_AUTORES_URL:https://biblioteca-evcwgpbpbwfqfnfh.westus2-01.azurewebsites.net/api/autores}
